### ISSUE TITLE
[README] - add presentation of this repo

### ISSUE THREAD

**Issue by nicolasdb** [Vulca/website#11]
I want to explain how to use this repo to all volonteer who want to help.

**Comment by AlexandreRousselet** [comment]
@nicolasdb ... any update about it ? 
I started to add new issues ... do you want me to write the read me too ?

**Comment by nicolasdb** [comment]
you can start to explain why this repo. 
I wanted to explain how to use it, but it will be for after my job in Norway, after the 10
