### ISSUE TITLE
Paulo Rosa Report - disappear (Phone size)

### ISSUE THREAD

**Issue by AlexandreRousselet** [Vulca/website#14]
With a phone, the Paulo Rosa report disappear: 
https://vulca.eu/pilotproject/

**Comment by nififre** [comment]
Can you check if this issue is still alive ?
I just checked it and on my phone there are still the reports.
If you can, please, send us a catchscreen here.

**Comment by AlexandreRousselet** [comment]
@nififre here it is how it looks on my phone
Pictures = 2 lines =/ 
![screenshot_20190601-170001](https://user-images.githubusercontent.com/45399609/58750137-c3fef800-848e-11e9-903f-6001f57f26ea.jpg)

**Comment by nififre** [comment]
Thank you. It's solved.
