### ISSUE TITLE
Contact us - wrong redirection

### ISSUE THREAD

**Issue by AlexandreRousselet** [Vulca/website#15]
I can send an email to vulca with contact us 
BUT 
After sending an email I get this page ... And I don't want it 

<img width="1210" alt="Screenshot 2019-05-27 at 12 44 18" src="https://user-images.githubusercontent.com/45399609/58414933-2d40ce80-807d-11e9-8f2b-0e0da760e99b.png">

**Comment by Thomas0sanz** [comment]
Tu atterris sur la page après avoir envoyer un mail?
