### ISSUE TITLE
🇭🇷Seminar - Phone: wrong background Images and color

### ISSUE THREAD

**Issue by AlexandreRousselet** [Vulca/website#21]
On phone (oneplus5) I figure out some issues Charles

- [ ] 1) background picture is wrong
and also
- [ ] 2) Colour font is blue on phone but yellow on laptop

[Color decimal there](https://docs.google.com/document/d/1cpGpJidqxIe7H8cZCXi6YrCXEnlL0TJoOMN-nd3i4z8/edit)

**Comment by AlexandreRousselet** [comment]
![screenshot_20190915-215810](https://user-images.githubusercontent.com/45399609/65251915-6b647100-daf8-11e9-9877-f746ae5260d5.jpg)
![Uploading screenshot_20190915-220114.jpg…]()

**Comment by AlexandreRousselet** [comment]
![screenshot_20190915-220114](https://user-images.githubusercontent.com/45399609/65251973-7b7c5080-daf8-11e9-8d11-50ec933c7181.jpg)

**Comment by AlexandreRousselet** [comment]
![screenshot_20190915-215810](https://user-images.githubusercontent.com/45399609/65251997-833bf500-daf8-11e9-9519-050919390861.jpg)

**Comment by charlespv** [comment]
I choose to remove background image from these blocks in order to reduce memory amount of the page when charging on a mobile device
