### ISSUE TITLE
Small other update needed 

### ISSUE THREAD

**Issue by AlexandreRousselet** [Vulca/website#24]
Mainly for @charlespv : 

- [x] We need to switch off the "Seminar Page" (the previous one). (https://vulca.eu/seminar/)
Because when we look on google with key words like: "Vulca, Seminar" we get the old page.  

- [x] Wrong link: VULCA SEMINAR - Home page 
Also, we need to update the link linked to the Vulca Seminar on the home page and also, everywhere the previous link was before. 
Wrong: https://vulca.eu/seminar/ 
Right: https://vulca.eu/vulca-seminar-2020/

- [x] Call to action: PARTICIPATE 
Please can we call it: **"Book your Ticket"** 

- [x] Changing Cover 
We need to change the banner because it is not allowed to use the arduino logo without permission. We adapted a new design without this logo. 
Find the updated cover [here](https://drive.google.com/drive/u/0/folders/1Fah7dmFukzTZGK_fVDKyxdJookcMg-gv) 
- [x] Also @charlespv can you add 2 or 3 more call to action "Book your ticket" along the webpage?

**Comment by charlespv** [comment]
Those two links (https://vulca.eu/seminar/) (https://vulca.eu/vulca-seminar-2020/) are now pointing to the same page. /seminar/ remain the principale entry link for Seminar and each year will create a new page and new redirection. The redirection is easy. It was done with a wordpress plugin.
