### ISSUE TITLE
Images are a bit too heavy on the Seminar 2020 page

### ISSUE THREAD

**Issue by jakubczaplicki** [Vulca/website#33]
The seminar page seems to be slow. I've run an online analysis tool and it indeed shows that the images are a bit too large: https://www.dareboost.com/en/report/d_25dc47dd6a0612f2296e4e6ec?reportIds=d_25dc47dd6a0612f2296e4e6ec

You could consider optimising the size of the photos.

**Comment by charlespv** [comment]
Thanks @jakubczaplicki for this issues. I installed a wordpress plugin to do not have this issues anymore. Some pictures are still heavy. They need adhoc processing

**Comment by jakubczaplicki** [comment]
Hi @charlespv  . yup.. the plugin doesn't seem to do much improvement : https://www.dareboost.com/en/report/d_15dca681090b998668437dc49?reportIds=d_15dca681090b998668437dc49
