### ISSUE TITLE
Facilities for Seminar

### ISSUE THREAD

**Issue by AlexandreRousselet** [Vulca/website#37]
It is time to give more info about logistic regarding the seminar.

@charlespv, here you have all the information regarding:

- [ ] Venue 
- [ ] Lunch & coffee break
- [ ] official language
- [ ] visa
- [ ] how to arrive to zadar
- [ ] housing option

--> Info here https://drive.google.com/drive/u/0/folders/1carK-tF9CqUdwyU4fj0xjGkmTmeGZoo0

- [ ] And also a short overview of Zadar if you want If you get enough time to include it nicely somewhere.

_Reminder_
Another site for inspiration: http://www.creativeforum.si/

**Comment by charlespv** [comment]
@AlexandreRousselet First version done, waiting for validation before closing the issue
